# Generated by Django 5.2.3 on 2025-07-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='question_detail',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('javascript', 'Javascript'), ('react', 'React'), ('python', 'Python'), ('nodejs', 'Nodejs'), ('css', 'Css'), ('typescript', 'Typescript'), ('database', 'Database'), ('api', 'Api'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forum.tag'),
        ),
    ]
